spring.application.name=jeju

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# \uCFFC\uB9AC + \uC2E4\uD589\uC2DC\uAC04
logging.level.jdbc.sqltiming=INFO
# \uACB0\uACFC \uD14C\uC774\uBE14 \uD615\uD0DC\uB85C \uCD9C\uB825
logging.level.jdbc.resultsettable=INFO
logging.level.jdbc.audit=OFF
logging.level.jdbc.resultset=OFF
logging.level.jdbc.connection=OFF

# JWT
jwt.secret=${JWT_SECRET}
# 30\uBD84
jwt.access-token-validity=${JWT_ACCESS_TOKEN_VALIDITY}
# 14\uC77C
jwt.refresh-token-validity=${JWT_REFRECH_TOKEN_VALIDITY}

#API \uAD00\uB828
api.mobile.os=${MOBILE_OS}
api.mobile.app=${MOBILE_APP}

#\uD55C\uAD6D\uAD00\uAD11\uACF5\uC0AC_\uAD6D\uBB38 \uAD00\uAD11\uC815\uBCF4 \uC11C\uBE44\uC2A4_GW
ks.key=${KS_KEY}
ks.url=${KS_URL}