spring.application.name=jeju

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# \uCFFC\uB9AC + \uC2E4\uD589\uC2DC\uAC04
logging.level.jdbc.sqltiming=INFO
# \uACB0\uACFC \uD14C\uC774\uBE14 \uD615\uD0DC\uB85C \uCD9C\uB825
logging.level.jdbc.resultsettable=INFO
logging.level.jdbc.audit=OFF
logging.level.jdbc.resultset=OFF
logging.level.jdbc.connection=OFF

logging.level.com.trip.jeju=DEBUG

# Swagger \uAD00\uB828 \uB85C\uADF8 \uB044\uAE30
logging.level.springdoc=WARN
logging.level.io.swagger=WARN
logging.level.org.springdoc=WARN

#logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=${JWT_SECRET}
# 30\uBD84
jwt.access-token-validity=${JWT_ACCESS_TOKEN_VALIDITY}
# 14\uC77C
jwt.refresh-token-validity=${JWT_REFRECH_TOKEN_VALIDITY}

#API \uAD00\uB828
api.mobile.os=${MOBILE_OS}
api.mobile.app=${MOBILE_APP}

#\uD55C\uAD6D\uAD00\uAD11\uACF5\uC0AC_\uAD6D\uBB38 \uAD00\uAD11\uC815\uBCF4 \uC11C\uBE44\uC2A4_GW
ks.key=${KS_KEY}
ks.url=${KS_URL}

# \uCE74\uCE74\uC624
oauth.kakao.client-id=${OAUTH_KAKAO_CLIENT_ID}
oauth.kakao.client-secret=${OAUTH_KAKAO_CLIENT_SECRET}
oauth.kakao.redirect-uri=${OAUTH_REDIRECT_URI}

# \uAD6C\uAE00
oauth.google.client-id=${OAUTH_GOOGLE_CLIENT_ID}
oauth.google.client-secret=${OAUTH_GOOGLE_CLIENT_SECRET}
oauth.google.redirect-uri=${OAUTH_REDIRECT_URI}

# \uB124\uC774\uBC84
oauth.naver.client-id=${OAUTH_NAVER_CLIENT_ID}
oauth.naver.client-secret=${OAUTH_NAVER_CLIENT_SECRET}
oauth.naver.redirect-uri=${OAUTH_REDIRECT_URI}